# 로컬 설정
spring:
  config:
    activate:
      on-profile: local  # 로컬 프로필일 때만 활성화
  datasource:
    # H2 메모리 DB 사용 (서버 재시작 시 데이터 초기화)
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true # 한줄로 길게 나오는 SQL을 읽기 좋게 여러 줄로 정렬
        use_sql_comments: true # 이 SQL이 어떤 메서드나 클래스 때문에 실행된 건지 주석으로 달아줘서 디버깅이 빠름
management:
  endpoint:
    health:
      show-details: always # 로컬에서 DB 연결 상태 등을 상세히 확인하기 위함